import 'package:file_picker/file_picker.dart';
import 'package:get/get.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../../data/models/article.dart';

class ArticleController extends GetxController {
  final _supabase = Supabase.instance.client;

  // Observables
  final isLoading = false.obs;
  final isUploading = false.obs;
  final articles = <Article>[].obs;

  @override
  void onInit() {
    super.onInit();
    fetchArticles();
  }

  /// Fetch all published articles with author profile info
  Future<void> fetchArticles() async {
    try {
      isLoading.value = true;
      final response = await _supabase
          .from('articles')
          .select('*, profiles(username, avatar_url)')
          .eq('is_published', true)
          .order('created_at', ascending: false);

      final data = response as List<dynamic>;
      articles.value = data.map((e) => Article.fromMap(e)).toList();
    } catch (e) {
      Get.snackbar('Error', 'Failed to load articles: $e');
    } finally {
      isLoading.value = false;
    }
  }

  /// Create a new article
  Future<bool> publishArticle({
    required String title,
    required dynamic contentJson,
    String? summary,
    PlatformFile? coverFile,
  }) async {
    try {
      isUploading.value = true;
      final userId = _supabase.auth.currentUser?.id;
      if (userId == null) {
        Get.snackbar('Error', 'Please login first');
        return false;
      }

      String? coverUrl;

      // 1. Upload Cover if exists
      if (coverFile != null) {
        final bytes = coverFile.bytes;
        final fileExt = coverFile.name.split('.').last;
        final fileName = '${DateTime.now().millisecondsSinceEpoch}.$fileExt';
        final filePath = '$userId/$fileName';

        if (bytes != null) {
          await _supabase.storage
              .from('article_covers')
              .uploadBinary(
                filePath,
                bytes,
                fileOptions: const FileOptions(
                  contentType:
                      'image/jpeg', // Adjust based on file type if needed
                  upsert: true,
                ),
              );

          coverUrl = _supabase.storage
              .from('article_covers')
              .getPublicUrl(filePath);
        }
      }

      // 2. Insert Article Record
      final article = Article(
        id: '', // Generated by DB
        userId: userId,
        title: title,
        summary: summary,
        coverUrl: coverUrl,
        content: contentJson,
        createdAt: DateTime.now(),
      );

      await _supabase.from('articles').insert(article.toMap());

      // 3. Refresh list
      fetchArticles();

      Get.snackbar('Success', 'Article published!');
      return true;
    } catch (e) {
      Get.snackbar('Error', 'Failed to publish article: $e');
      return false;
    } finally {
      isUploading.value = false;
    }
  }
}
